### ISSUE TITLE
Replaced in The Ecosystem

### ISSUE THREAD

**Issue by zoffixznet** [carbin/p6-Crypt-Bcrypt#6]
Hi,

Just an FYI: it appears this module is currently broken as it uses some of the featured that did not make it into `6.c` Perl 6 (e.g. `@*INC`).

Another volunteer rewrote the module entirely and they've added their work to the ecosystem, removing yours, to avoid user confusion.

If you wish to fix the issues and have you work readded, just submit a PR by adding the URL to raw META file to [META.list file in the ecosystem](https://github.com/perl6/ecosystem/blob/master/META.list)

I'm just letting you know this, so you don't think we willy-nilly removed you.

Cheers,
ZZ

**Comment by carbin** [comment]
I had planned to fix this but never got around to it, so it's good to see someone else has picked it up. Thanks for letting me know.
